spring.application.name=amway

spring.data.redis.host=${REDISHOST:${SPRING_REDIS_HOST:${REDIS_HOST:localhost}}}
spring.data.redis.port=${REDISPORT:${SPRING_REDIS_PORT:${REDIS_PORT:6379}}}
spring.data.redis.password=${REDISPASSWORD:${SPRING_REDIS_PASSWORD:${REDIS_PASSWORD:}}}
